### PR TITLE
Configure site layout

### LINKED ISSUE #527: Configure Site Layout
**Is your feature request related to a problem? Please describe.**
The site still needs a working layout component. This is the component that all pages render inside - it renders the site background, site header, and side navbar and then renders the page inside the site body.

**Describe the solution you'd like**
Build a site layout component as shown in [this mockup](../blob/main/public/images/mockups/siteLayout/mockup.png), with the changes noted in [its readme](../blob/main/public/images/mockups/siteLayout/README.md). Once the component is functional a draft PR may be submitted, but it should not be marked `Ready` until the component is fully styled.

**Describe alternatives you've considered**
N/A. This is a required feature.

**Additional context**

I [took a stab](../blob/main/src/components/layout/layout.tsx) at using Mantine's [AppShell component](https://mantine.dev/core/app-shell/) to do this, but didn't get it working. I already configured the site's [Head component](../blob/main/src/components/layout/customHead.tsx). 

I also tried implementing the [NavBar](../blob/main/src/components/layout/navbar.tsx), but got sidetracked and haven't gotten back to it. Ideally this will use Mantine's [NavBar component](https://mantine.dev/core/app-shell/#navbar-and-aside-components) to do this, but building it from scratch would work too.

### PR DESCRIPTION
**Pull request by ShouvikGhosh2048**
This PR closes #527.

### CODE REVIEW

**Comment by ShouvikGhosh2048** [comment]
@otobot1

Still a work in progress but you can try it out at `http://localhost:3000/home` if you want.

Current state:
celeste_mod_list_site_layout_1
celeste_mod_list_site_layout_2

1) How should the navbar change with smaller widths?
2) I'm not familiar with Mantine. For styling I'm currently using inline styles + the [sx prop](https://mantine.dev/styles/sx/). I also noticed [createStyles](https://mantine.dev/styles/create-styles/) has been used in the project. Which one do you prefer?

**Comment by otobot1** [comment]
> 

1. Something like [this](https://mantine.dev/app-shell-demo-alt/) please. If it gives you too much trouble, feel free to leave smaller screens as a follow-up issue. My plan was to just develop for `720p` and above and deal with small screens later. 
2. Please use `createStyles` when possible - I find the code much easier to follow when most of the styling is outside of the component (in the `createStyles` hook) and in the component you only deal with class names and maybe some conditional logic with the `cx` function. Check out [this file](https://github.com/icflorescu/mantine-datatable/blob/main/package/DataTableRowExpansion.tsx) from the [Mantine DataTable source code](https://github.com/icflorescu/mantine-datatable/tree/main/package) for an example of my preferred coding style for styling.

**Comment by otobot1** [comment]
Oh also, here's [a spreadsheet](https://docs.google.com/spreadsheets/d/10usmAn1GeLTxU3NeGM5C29QWC4UJ1-g2tWJ-cqJCEUY/edit#gid=0) with the color codes that we picked out while designing the mockups. The colored-in cells are the shades we actually used.

**Comment by ShouvikGhosh2048** [comment]
@otobot1 

The PR is ready for review. I haven't implemented the responsive navbar, I'll leave it as a follow up issue. You can check the updated layout at the `/` and `/mods` routes.

1) I'm not using AppShell. The site layout design has the header, content, and footer in the center and the navbar floating on the left - which is different from AppShell's layout. I used a Grid instead.
2) Is the navigation broken from `/mods` to `/` for you? It seems broken when I try navigating within the same tab, but when I open `/` in a new tab it works. Does this have to do with errors on the `/mods` page?

**Comment by otobot1** [comment]
> @otobot1
> 
> The PR is ready for review. I haven't implemented the responsive navbar, I'll leave it as a follow up issue. You can check the updated layout at the `/` and `/mods` routes.
> 
> 1. I'm not using AppShell. The site layout design has the header, content, and footer in the center and the navbar floating on the left - which is different from AppShell's layout. I used a Grid instead.
> 2. Is the navigation broken from `/mods` to `/` for you? It seems broken when I try navigating within the same tab, but when I open `/` in a new tab it works. Does this have to do with the errors on the `/mods` page?

Awesome! I'll try and have a look at it this weekend. As for your other questions:
1. 👍 
2. *Probably,* but I'll have to double check. If you're curious in the meantime, just replace those `<MultiSelect>` elements with empty `<div>`s and it should fix the errors.

**Review by otobot1 — CHANGES_REQUESTED** [review]
Thanks for getting this working! I do have a few notes that need to be resolved before merging though:
1. Center and enlarge the site title (the `Celeste Mods List` text in the header) to more closely match the mockup.
2. Enlarge the Navbar elements to more closely match the mockup. Maybe by ~20%?
3. Add maybe 15px of left and right padding to the inner footer.
4. ~~Style the background so that its level of zoom doesn't depend on the height of the page content. For what I mean, compare `Home` and `/mods`, and compare `/mods` with 10 mods vs 250 mods (or just make the window narrower).~~ Actually, please make it so that the pages just have a constant height, and wrap the pages in a [ScrollArea](https://mantine.dev/core/scroll-area/).

A couple of other things that can be left as follow-up issues:
1. The link from `/mods` to `Home` is still broken for me, even after resolving the errors on `/mods`. We'll have to figure this out before we launch.
2. At some point we will want to remove the `Layout` component from the individual pages and import it in [_app.tsx](../blob/main/src/pages/_app.tsx) instead. This will save a tiny bit of code, and will be a bit more efficient for rendering pages. In order to implement this, the `Layout` component will need to be refactored to use the current URL from the Next.js router, instead of strings passed in from the page. Alternatively, the `Layout` could pass a setState function down to the page for it to set.

Thanks again for your help!

**Comment by ShouvikGhosh2048** [comment]
@otobot1

I've made the requested changes.

The mods table doesn't behave properly with ScrollArea, as you can see below.

scroll-and-datatable

**Comment by otobot1** [comment]
> @otobot1
> 
> I've made the requested changes.
> 
> The mods table doesn't behave properly with ScrollArea, as you can see below.
> 
> scroll-and-datatable

Apparently Mantine Datatable [embeds its own ScrollArea](https://icflorescu.github.io/mantine-datatable/examples/scrollable-vs-auto-height). In this case, we can just give the page a max height and let the datatable handle the scrolling. I'll try and review the changes more fully in the next few days.

**Review by otobot1 — DISMISSED** [review]

**Comment by otobot1** [comment]
> Thanks for getting this working! I do have a few notes that need to be resolved before merging though:
> 
> 1. Center and enlarge the site title (the `Celeste Mods List` text in the header) to more closely match the mockup.
> 2. Enlarge the Navbar elements to more closely match the mockup. Maybe by ~20%?
> 3. Add maybe 15px of left and right padding to the inner footer.
> 4. ~Style the background so that its level of zoom doesn't depend on the height of the page content. For what I mean, compare `Home` and `/mods`, and compare `/mods` with 10 mods vs 250 mods (or just make the window narrower).~ Actually, please make it so that the pages just have a constant height, and wrap the pages in a [ScrollArea](https://mantine.dev/core/scroll-area/).
> 
> A couple of other things that can be left as follow-up issues:
> 
> 1. The link from `/mods` to `Home` is still broken for me, even after resolving the errors on `/mods`. We'll have to figure this out before we launch.
> 2. At some point we will want to remove the `Layout` component from the individual pages and import it in [_app.tsx](../blob/main/src/pages/_app.tsx) instead. This will save a tiny bit of code, and will be a bit more efficient for rendering pages. In order to implement this, the `Layout` component will need to be refactored to use the current URL from the Next.js router, instead of strings passed in from the page. Alternatively, the `Layout` could pass a setState function down to the page for it to set.
> 
> Thanks again for your help!

I had a bit of time tonight, so I reviewed the changes. 1 and 2 were perfect. 3 wasn't what I had in mind, but I did a *very* bad job of explaining what I wanted, so that's on me. I managed to figure it out though, so the only one left is 4. 

As you pointed out, adding our own ScrollArea wasn't a good solution. After learning that the datatable [has its own ScrollArea](https://icflorescu.github.io/mantine-datatable/examples/scrollable-vs-auto-height), I think the datatable should handle all of the scrolling. In order to achieve this, the Grid needs to be refactored to have nesting similar to the third component on [this page](https://ui.mantine.dev/category/grids). I ran out of time for now, but I should be able to get to it some time this weekend. If you would like (and if my explanation actually makes sense), feel free to take a stab at it first.

**Comment by otobot1** [comment]
> Thanks for getting this working! I do have a few notes that need to be resolved before merging though:
> 
> 1. Center and enlarge the site title (the `Celeste Mods List` text in the header) to more closely match the mockup.
> 2. Enlarge the Navbar elements to more closely match the mockup. Maybe by ~20%?
> 3. Add maybe 15px of left and right padding to the inner footer.
> 4. ~Style the background so that its level of zoom doesn't depend on the height of the page content. For what I mean, compare `Home` and `/mods`, and compare `/mods` with 10 mods vs 250 mods (or just make the window narrower).~ Actually, please make it so that the pages just have a constant height, and wrap the pages in a [ScrollArea](https://mantine.dev/core/scroll-area/).
> 
> A couple of other things that can be left as follow-up issues:
> 
> 1. The link from `/mods` to `Home` is still broken for me, even after resolving the errors on `/mods`. We'll have to figure this out before we launch.
> 2. At some point we will want to remove the `Layout` component from the individual pages and import it in [_app.tsx](../blob/main/src/pages/_app.tsx) instead. This will save a tiny bit of code, and will be a bit more efficient for rendering pages. In order to implement this, the `Layout` component will need to be refactored to use the current URL from the Next.js router, instead of strings passed in from the page. Alternatively, the `Layout` could pass a setState function down to the page for it to set.
> 
> Thanks again for your help!

I had a bit of time tonight, so I reviewed the changes. 1 and 2 were perfect. 3 wasn't what I had in mind, but I did a *very* bad job of explaining what I wanted, so that's on me. I managed to figure it out though, so the only one left is 4. 

As you pointed out, adding our own ScrollArea wasn't a good solution. After learning that the datatable [has its own ScrollArea](https://icflorescu.github.io/mantine-datatable/examples/scrollable-vs-auto-height), I think the datatable should handle all of the scrolling. In order to achieve this, the Grid needs to be refactored to have nesting similar to the third component on [this page](https://ui.mantine.dev/category/grids). I ran out of time for now, but I should be able to get to it some time this weekend. If you would like (and if my explanation actually makes sense), feel free to take a stab at it first.

**Comment by ShouvikGhosh2048** [comment]
Hi, I'm not sure why we need to refactor the grid - doesn't setting the height of `<main>` and `datatable` work?

I tried this out:
```
diff --git a/src/components/layout/layout.tsx b/src/components/layout/layout.tsx
index 571f2f1..e1afe3c 100644
--- a/src/components/layout/layout.tsx
+++ b/src/components/layout/layout.tsx
@@ -25,7 +25,7 @@ const useStyles = createStyles(() => ({
     },
     children: {
         backgroundColor: "rgba(1.0, 1.0, 1.0, 0.9)",
-        minHeight: "100%",
+        height: '750px',
         padding: "5px 45px",
     },
 }));
diff --git a/src/pages/mods/index.tsx b/src/pages/mods/index.tsx
index 1cc63ba..944ce4f 100644
--- a/src/pages/mods/index.tsx
+++ b/src/pages/mods/index.tsx
@@ -550,6 +550,7 @@ const Mods: NextPage = () => {
                         );
                     },
                 }}
+                height={700}
                 withBorder
                 borderRadius={"sm"}
                 striped
```

height-example

**Comment by otobot1** [comment]
> Hi, I'm not sure why we need to refactor the grid - doesn't setting the height of `<main>` and `datatable` work?
> 
> I tried this out:
> 
> ```
> diff --git a/src/components/layout/layout.tsx b/src/components/layout/layout.tsx
> index 571f2f1..e1afe3c 100644
> --- a/src/components/layout/layout.tsx
> +++ b/src/components/layout/layout.tsx
> @@ -25,7 +25,7 @@ const useStyles = createStyles(() => ({
>      },
>      children: {
>          backgroundColor: "rgba(1.0, 1.0, 1.0, 0.9)",
> -        minHeight: "100%",
> +        height: '750px',
>          padding: "5px 45px",
>      },
>  }));
> diff --git a/src/pages/mods/index.tsx b/src/pages/mods/index.tsx
> index 1cc63ba..944ce4f 100644
> --- a/src/pages/mods/index.tsx
> +++ b/src/pages/mods/index.tsx
> @@ -550,6 +550,7 @@ const Mods: NextPage = () => {
>                          );
>                      },
>                  }}
> +                height={700}
>                  withBorder
>                  borderRadius={"sm"}
>                  striped
> ```
> 
> height-example

That does work (with 600px and 550px instead of 750 and 700 to ensure the page doesn't have to scroll on 1080p), but I want to try and avoid using `px` if we can - it doesn't respond to different screen resolutions. I have a bit of time now so I'll give the refactoring a try.

**Pull request merged**
